title: SciTech
# CHANGE THIS: Add your repository name here
baseurl: "/SciTech" 
url: "https://alessacsardi.github.io"

# Relaxing Aura Palette
colors:
  beige: "#f4efe6"
  emerald: "#0b3d2e"
  gold: "#D5B038"
  text: "#2b2b2b"

# Ensure Jekyll doesn't use the default theme that is overriding your styles
theme: none
